Repository citrushack/citrushack2023, pull requests merged in 2023-03, with the labels that each got.

#73 add font family and import fonts
  styles/globals.css
Labels: rfr, frontend

#80 Updated Schedule Section
  components/Schedule.tsx
  pages/index.tsx
  pages/sections/schedule.tsx
  public/assets/balloonBlue.svg
  public/assets/balloonBlueTilt.svg
  public/assets/balloonOrange.svg
  public/assets/balloonRed.svg
  public/assets/balloonYellow.svg
  public/assets/cloud.svg
  public/assets/dayOneFlag.svg
  public/assets/dayTwoFlag.svg
  public/assets/reverseDayOneFlag.svg
  public/assets/reverseDayTwoFlag.svg
  public/assets/schedule.svg
  styles/globals.css
Labels: rfr, frontend

#81 :lipstick: spiced up tracks section
  pages/index.tsx
  pages/sections/about.tsx
  pages/sections/landing.tsx
  pages/sections/schedule.tsx
  pages/sections/tracks.tsx
  public/assets/sponsor3.svg
Labels: rfr, frontend

#82 Made About Us Smaller cause minsoo hated OG
  cypress/e2e/loading.cy.ts
  pages/sections/about.tsx
  public/assets/aboutUs.svg
  public/assets/suitcases.svg
Labels: frontend

#91 faq updated
  components/FAQ.tsx
Labels: rfr, frontend

#92 about us updated
  public/assets/aboutUs.svg
Labels: rfr, frontend

#93 added address and stamp
  public/assets/aboutUs.svg
Labels: rfr, frontend

#90 Team Passports
  components/Passport.tsx
  components/Passports.tsx
  pages/index.tsx
  tailwind.config.js
Labels: rfr, frontend

#85 Fixed the complaints
  components/Countdown.tsx
  components/FAQ.tsx
  components/Nav.tsx
  components/Passport.tsx
  components/Passports.tsx
  components/Schedule.tsx
  components/UserBar/ThemeButton.tsx
  pages/index.tsx
  pages/sections/about.tsx
  pages/sections/landing.tsx
  pages/sections/sponsors.tsx
  pages/sections/support.tsx
  pages/sections/tracks.tsx
  public/assets/aboutBG.svg
  public/assets/airplane.svg
  public/assets/bird1.svg
  public/assets/bird2.svg
  public/assets/bird3.svg
  public/assets/cloud2.svg
  public/assets/cloudDark.svg
  public/assets/cloudDark2.svg
  public/assets/cutieFlag.svg
  public/assets/globeLight.svg
  public/assets/landing.svg
  public/assets/orangeFlag.svg
  public/assets/skyline.svg
  public/assets/skylineDark.svg
  public/assets/sponsors/blackstone.svg
  public/assets/sponsors/redbull.svg
  public/assets/sponsors/skylineDark.svg
  public/assets/sponsors/ucr.svg
  public/assets/star.svg
  public/assets/tangerineFlag.svg
  public/team/alex.png
  public/team/ashley.png
  public/team/gab.png
  public/team/henry.png
  public/team/jon.png
  public/team/kanin.png
  public/team/mariam.png
  public/team/minsoo.png
  public/team/paulian.png
  public/team/prathmesh.png
  public/team/sarah.png
  public/team/vivian.png
  styles/globals.css
  tailwind.config.js
Labels: rfr, frontend

#100 Golwallakoala
  public/assets/sponsors/become_mentor_front.svg
  public/assets/sponsors/sponsor_us_back.svg
  public/assets/sponsors/sponsor_us_front.svg
Labels: rfr, frontend

#98 Updated Landing w Globe
  pages/index.tsx
  pages/sections/about.tsx
  pages/sections/landing.tsx
  pages/sections/schedule.tsx
  pages/sections/sponsors.tsx
  pages/sections/support.tsx
  pages/sections/team.tsx
  public/assets/aboutBGDark.svg
  public/assets/aboutUs.svg
  public/assets/globeDark.svg
  public/assets/postcard.svg
  public/assets/waves/supportWave.svg
  public/assets/waves/supportWaveDark.svg
  public/assets/waves/teamWave.svg
  public/assets/waves/teamWaveDark.svg
Labels: frontend

#108 :bug: slave work ordered by mika
  components/SupportCards.tsx
  package.json
  pages/sections/support.tsx
  tailwind.config.js
  yarn.lock
Labels: rfr

#102 Waves and Random Ass Assets
  components/FAQ.tsx
  components/Footer.tsx
  components/ProfileWrapper.tsx
  components/Schedule.tsx
  components/SponsorGrid.tsx
  pages/index.tsx
  pages/sections/about.tsx
  pages/sections/faq.tsx
  pages/sections/landing.tsx
  pages/sections/schedule.tsx
  pages/sections/sponsors.tsx
  pages/sections/support.tsx
  pages/sections/team.tsx
  pages/sections/tracks.tsx
  public/assets/balloon24.svg
  public/assets/balloon500.svg
  public/assets/balloon5k.svg
  public/assets/bus_footer.svg
  public/assets/bus_footer_dark.svg
  public/assets/cloud.svg
  public/assets/cloudDark.svg
  public/assets/globalCommunity.svg
  public/assets/newFrontiers.svg
  public/assets/studentCommunity.svg
  public/assets/sustainability.svg
  public/assets/tiersFlag.svg
  public/assets/tiltedPlane.svg
  public/assets/waves/footer_wave.svg
  public/assets/waves/footer_wave_dark.svg
Labels: rfr
