Repository citrushack/citrushack2023, pull requests merged in 2023-04, with the labels that each got.

#97 Modal background dimming
  components/Modal.tsx
Labels: enhancement, frontend

#113 Update Sponsor, SponsorGrid
  components/SponsorGrid.tsx
  public/assets/sponsors/acm.webp
  public/assets/sponsors/aspb.png
  public/assets/sponsors/aspb.svg
  public/assets/sponsors/balsamiq.png
  public/assets/sponsors/blackstone.png
  public/assets/sponsors/coolerMaster.png
  public/assets/sponsors/desmos.png
  public/assets/sponsors/echo3d.png
  public/assets/sponsors/gcap.png
  public/assets/sponsors/glico.png
  public/assets/sponsors/googleCloud.svg
  public/assets/sponsors/redbull.png
  public/assets/sponsors/sketch.png
  public/assets/sponsors/stickermule.png
  public/assets/sponsors/tensorflow.png
  public/assets/sponsors/triad.png
  public/assets/sponsors/ucrBotanic.png
  public/assets/sponsors/wolfram.png
  tailwind.config.js
Labels: frontend

#110 Last Things From Mikuuu
  components/FAQ.tsx
  components/Footer.tsx
  components/MLHBanner.tsx
  components/ProfileWrapper.tsx
  components/Schedule.tsx
  components/SponsorGrid.tsx
  components/SupportCards.tsx
  pages/index.tsx
  pages/sections/about.tsx
  pages/sections/faq.tsx
  pages/sections/landing.tsx
  pages/sections/schedule.tsx
  pages/sections/sponsors.tsx
  pages/sections/support.tsx
  pages/sections/team.tsx
  pages/sections/tracks.tsx
  public/assets/bus_footer.svg
  public/assets/bus_footer_dark.svg
  public/assets/orangeFlag.svg
  public/assets/vercel.svg
  public/assets/waves/scheduleWave.svg
  public/assets/waves/scheduleWaveDark.svg
  public/assets/waves/sponsorBGDarkDesktop.svg
  public/assets/waves/sponsorBGDarkMobile.svg
  public/assets/waves/sponsorBGDarkTablet.svg
  public/assets/waves/sponsorBGLightDesktop.svg
  public/assets/waves/sponsorBGLightMobile.svg
  public/assets/waves/sponsorBGLightTablet.svg
  public/team/alex.png
  public/team/kanin.png
Labels: frontend

#115 Complaint Hotline
  components/FAQ.tsx
  components/Footer.tsx
  components/MLHBanner.tsx
  components/ProfileWrapper.tsx
  components/Schedule.tsx
  components/SponsorGrid.tsx
  components/SupportCards.tsx
  pages/index.tsx
  pages/sections/faq.tsx
  pages/sections/landing.tsx
  pages/sections/schedule.tsx
  pages/sections/support.tsx
  pages/sections/team.tsx
  public/assets/waves/scheduleWave2.svg
  public/assets/waves/scheduleWave2Dark.svg
  public/assets/waves/scheduleWave3.svg
  public/assets/waves/scheduleWave3Dark.svg
  public/assets/waves/sponsorBGDarkDesktop.svg
  public/assets/waves/sponsorBGDarkMobile.svg
  public/assets/waves/sponsorBGDarkTablet.svg
  public/assets/waves/sponsorBGLightDesktop.svg
  public/assets/waves/sponsorBGLightMobile.svg
  public/assets/waves/sponsorBGLightTablet.svg
  styles/globals.css
  tailwind.config.js
Labels: frontend

#116 FIGMA-D THE SPONSOR BG
  pages/sections/team.tsx
  public/assets/waves/sponsorBGDarkDesktop.svg
  public/assets/waves/sponsorBGDarkMobile.svg
  public/assets/waves/sponsorBGDarkTablet.svg
  public/assets/waves/sponsorBGLightDesktop.svg
  public/assets/waves/sponsorBGLightMobile.svg
  public/assets/waves/sponsorBGLightTablet.svg
Labels: rfr, FINAL PUSH

#130 Added orange coast college
  components/Form/ApplicationForm/schools.tsx
Labels: rfr

#137 Unnecessary Complaints Hotline
  components/ExternalLink.tsx
  components/Footer.tsx
Labels: rfr

#139 🚨🚨Complaint Hotline Back UP 🚨🚨
  components/SponsorGrid.tsx
  pages/sections/team.tsx
  public/assets/sponsors/stickers.svg
Labels: rfr

#143 🐓 QR Codieee
  components/ExternalLink.tsx
  components/Schedule.tsx
  components/UserBar/UserDropdown.tsx
  pages/api/users/mark-canes-picked-up.ts
  pages/users/[id].tsx
Labels: rfr, backend
