Repository citrushack/citrushack2023, pull requests merged in 2023-02, with the labels that each got.

#41 test /apply page
  cypress.config.ts
  cypress/e2e/apply-page.cy.ts
  cypress/fixtures/session.json
  cypress/support/commands.ts
  cypress/tsconfig.json
  package.json
Labels: testing, rfr

#47 Fixed dropdown menu to fit within application box
  components/Form/components.tsx
Labels: rfr, frontend

#40 Added Favicon
  public/favicon.ico
  public/vercel.svg
Labels: rfr

#46 Display Apply Button on landing page when user has not applied yet
  pages/sections/landing.tsx
Labels: rfr, backend

#51 test application submit & log in/out
  .github/workflows/cypress.yml
  cypress/e2e/apply-page.cy.ts
  cypress/e2e/sign-in-out.cy.ts
  cypress/e2e/toggle-theme.cy.ts
  cypress/fixtures/count-in-person.json
  cypress/fixtures/count.json
  cypress/fixtures/session.json
  cypress/support/commands.ts
  cypress/support/e2e.ts
  cypress/tsconfig.json
Labels: testing, rfr

#54 Alamode89/in person
  components/FaqAccordion/components.tsx
  components/Form/ApplicationForm/components.tsx
  pages/sections/about.tsx
Labels: rfr, frontend

#56 colorpallete added
  pages/index.tsx
  styles/globals.css
  tailwind.config.js
Labels: frontend

#57 Created landing page
  components/Countdown/components.tsx
  components/SignupCounter.tsx
  pages/index.tsx
  pages/sections/landing.tsx
  public/assets/landing.svg
Labels: rfr, frontend

#61 color pallette updated
  pages/index.tsx
  pages/sections/landing.tsx
  styles/globals.css
  tailwind.config.js
Labels: rfr

#64 Created About Us Section
  components/Page/Nav.tsx
  pages/index.tsx
  pages/sections/about.tsx
  pages/sections/landing.tsx
  public/assets/postcard.svg
  public/assets/suitcases.svg
Labels: rfr, frontend
